apiVersion: v1
kind: Pod
metadata:
  name: sihang-autoalbument-50k-debug
  namespace: gp-engine-malof
  labels:
    app: sihang-autoalbument-50k-debug
spec:
  containers:
  - name: debug-container
    # image: ghcr.io/albumentations-team/autoalbument:latest
    image: gitlab-registry.nrp-nautilus.io/nrp/scientific-images/python:cuda-v1.5.0
    command: ["sleep", "infinity"]
    imagePullPolicy: Always
    resources:
      limits:
        cpu: '16'
        memory: 32Gi
        nvidia.com/a40: '1'
      requests:
        cpu: '8'
        memory: 32Gi
        nvidia.com/a40: '1'
    volumeMounts:
      - name: pvc-storage
        mountPath: /mnt/synrs3d
      - name: chuqiao-result
        mountPath: /mnt/styled
    securityContext:
      runAsUser: 0
  volumes:
    - name: pvc-storage
      persistentVolumeClaim:
        claimName: synrs3d-test
    - name: chuqiao-result
      persistentVolumeClaim:
        claimName: chuqiao-result-pvc