apiVersion: batch/v1
kind: Job
metadata:
  name: sihang-autoalbument-50k-job
  namespace: gp-engine-malof
  labels:
    job-name: sihang-autoalbument-50k-job
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 0
  template:
    metadata:
      labels:
        job-name: sihang-autoalbument-50k-job
    spec:
      restartPolicy: Never
      containers:
        - name: pvc-test-container
          # image: ghcr.io/albumentations-team/autoalbument:latest
          image: gitlab-registry.nrp-nautilus.io/nrp/scientific-images/python:cuda-v1.5.0
          imagePullPolicy: Always
          command:
            - /bin/bash
            - '-c'
          args:
            - |
              # Activate base environment
              source activate base

  
              # install git
              apt update && apt install git -y
              
              # Navigate to SynRS3D directory
              cd /mnt/synrs3d/SynRS3D
              nvidia-smi

              git checkout gaussian-baselines
              git pull
              git reset --hard origin/gaussian-baselines 

              cd autoalbument
              bash install_autoalbument.sh
              export HYDRA_FULL_ERROR=1
              conda activate autoalbument
              bash run_autoalbument.sh
              
              
          resources:
            limits:
              cpu: '32'
              memory: 64Gi
              nvidia.com/gpu: '1'
            requests:
              cpu: '16'
              memory: 64Gi
              nvidia.com/gpu: '1'
          volumeMounts:
            - name: pvc-storage
              mountPath: /mnt/synrs3d
            - name: chuqiao-result
              mountPath: /mnt/styled
          securityContext:
              runAsUser: 0
      volumes:
        - name: pvc-storage
          persistentVolumeClaim:
            claimName: synrs3d-test
        - name: chuqiao-result
          persistentVolumeClaim:
            claimName: chuqiao-result-pvc
      terminationGracePeriodSeconds: 30
  ttlSecondsAfterFinished: 86400