apiVersion: batch/v1
kind: Job
metadata:
  name: sihang-gaussian-50k-job
  namespace: gp-engine-malof
  labels:
    job-name: sihang-gaussian-50k-job
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 0
  template:
    metadata:
      labels:
        job-name: sihang-gaussian-50k-job
    spec:
      restartPolicy: Never
      containers:
        - name: pvc-test-container
          image: gitlab-registry.nrp-nautilus.io/nrp/scientific-images/python:cuda-v1.5.0
          imagePullPolicy: Always
          command:
            - /bin/bash
            - '-c'
          args:
            - |
              # Activate base environment
              source activate base

              # Create new conda environment
              conda create -n synrs3d python=3.11 -y

              # Activate the new environment
              source activate synrs3d

              # Install PyTorch with CUDA support
              # conda install pytorch=2.4.1 torchvision=0.19.1 torchaudio=2.4.1 pytorch-cuda=11.8 -c pytorch -c nvidia -y
              # conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia -y
              pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

              # Install GDAL
              conda install gdal -y

              # Check Python path
              which python


              # Install Python packages
              python -m pip install albumentations==2.0.5 tqdm ever-beta==0.2.3 huggingface_hub rasterio
              python -m pip install scikit-learn

              echo "albumentations installed"

              # Replace the albumentations transform file
              rm /opt/conda/envs/synrs3d/lib/python3.11/site-packages/albumentations/pytorch/transforms.py
              cp /mnt/synrs3d/swap_env_files/transforms.py /opt/conda/envs/synrs3d/lib/python3.11/site-packages/albumentations/pytorch/

              # Navigate to SynRS3D directory
              cd /mnt/synrs3d/SynRS3D

              git checkout gaussian-baselines
              # git pull --rebase
              git fetch --all
              git reset --hard origin/gaussian-baselines

              # Optional scripts to run
              # bash ./data/make_links.sh
              # bash /mnt/synrs3d/SynRS3D/so_style_100kit.sh 0.5
              # bash /mnt/synrs3d/SynRS3D/sourceonly_100kit.sh 0.5

              # Run evaluation script
              # bash /mnt/synrs3d/SynRS3D/eval_ss.sh >> /mnt/synrs3d/SynRS3D/eval_ss.log
              # cat /mnt/synrs3d/SynRS3D/eval_ss.log
              # bash /mnt/synrs3d/SynRS3D/eval_he.sh >> /mnt/synrs3d/SynRS3D/eval_he.log
              # cat /mnt/synrs3d/SynRS3D/eval_he.log

              # bash /mnt/synrs3d/SynRS3D/so_50kit_baseline.sh
              # bash /mnt/synrs3d/SynRS3D/so_50kit_gaussian.sh 
              bash /mnt/synrs3d/SynRS3D/eval_gaussian_bashline.sh  >> /mnt/synrs3d/SynRS3D/eval_gaussian_baseline.log
              
          resources:
            limits:
              cpu: '32'
              memory: 32Gi
              nvidia.com/gpu: '1'
            requests:
              cpu: '16'
              memory: 16Gi
              nvidia.com/gpu: '1'
          volumeMounts:
            - name: pvc-storage
              mountPath: /mnt/synrs3d
            - name: chuqiao-result
              mountPath: /mnt/styled
          securityContext:
              runAsUser: 0
      volumes:
        - name: pvc-storage
          persistentVolumeClaim:
            claimName: synrs3d-test
        - name: chuqiao-result
          persistentVolumeClaim:
            claimName: chuqiao-result-pvc
      terminationGracePeriodSeconds: 30
  ttlSecondsAfterFinished: 86400