---
apiVersion: v1
kind: Service
metadata:
  name: watcher-service
  namespace: gp-engine-malof
  labels:
    app: watcher
spec:
  type: ClusterIP
  selector:
    k8s-app: watcher
  ports:
  - name: 6006-port
    port: 6006
    targetPort: 6006
  - name: 6007-port
    port: 6007
    targetPort: 6007
  - name: 6008-port
    port: 6008
    targetPort: 6008
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: watcher-deployment
  labels:
    app: watcher
    k8s-app: watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watcher
      k8s-app: watcher
  template:
    metadata:
      labels:
        app: watcher
        k8s-app: watcher
    spec:
      containers:
      - image: tensorflow/tensorflow:latest
        imagePullPolicy: IfNotPresent
        command: ["sleep", "infinity"]
        name: watcher-container
        ports:
        - containerPort: 6006
        - containerPort: 6007
        - containerPort: 6008
        resources:
          limits:
            cpu: '2'
            memory: 8Gi
          requests:
            cpu: '1'
            memory: 4Gi 
        volumeMounts:
          - name: pvc-storage
            mountPath: /mnt/synrs3d
          - name: chuqiao-result
            mountPath: /mnt/styled
        securityContext:
          runAsUser: 0
      volumes:
        - name: pvc-storage
          persistentVolumeClaim:
            claimName: synrs3d-test
        - name: chuqiao-result
          persistentVolumeClaim:
            claimName: chuqiao-result-pvc